name: Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-js:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set registry authentication token
      run: echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install dependencies
      run: npm install

    - name: Run Vite
      run: npm run build

    - name: Check for uncommitted changes
      run: '[ -z "$(git status -s --porcelain)" ]'
