name: Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-js:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set registry authentication token
      run: echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install dependencies
      run: npm install

    # Clone core to get access to the variabley stylesheet
    - uses: actions/checkout@v1
      with:
        repository: biigle/core
        ref: master
        fetch-depth: 1
        path: core

    - name: Update variables stylesheet link
      run: ln -sf ../../../../core/resources/assets/sass/bootstrap/_variables.scss src/resources/assets/sass/_variables.scss

    - name: Run Vite
      run: npm run build

    - name: Check for uncommitted changes
      run: '[ -z "$(git status -s --porcelain)" ]'
